### ISSUE TITLE
Question about spread_tuned_p()

### ISSUE THREAD

**Issue by nathanhack** [JarekDuda/AsymmetricNumeralSystemsToolkit#2]
Hello I'm interested in using the results from spread_tuned_p() but I'm a bit unclear how to use it. 

Would it be possible to give us a concrete example that uses the results of spread_tuned_p() to compress a string?

**Comment by JarekDuda** [comment]
Hi, tuned spreads are used the same way as the remaining, with only difference of requiring both quantized and original distribution. Here is a paper: https://arxiv.org/pdf/2106.06438

They are for tANS ( https://en.wikipedia.org/wiki/Asymmetric_numeral_systems#Tabled_variant_(tANS) ) like FSE ( https://github.com/Cyan4973/FiniteStateEntropy ).

**Comment by nathanhack** [comment]
Thanks for the quick response. I appreciate you clarifying it was for the table variant.  I'll see if Yann is interested in adding the benefit found in spread_tuned_p(). Nevertheless, keep up the good work, I'm definitely interested in what you come up with next.
